# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Screen2(object):
    def setupUi(self, Screen2):
        Screen2.setObjectName("Screen2")
        Screen2.resize(300, 400)
        Screen2.setMinimumSize(QtCore.QSize(300, 400))
        Screen2.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(Screen2)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 140, 131, 51))
        self.pushButton.setObjectName("pushButton")

        Screen2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screen2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        Screen2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screen2)
        self.statusbar.setObjectName("statusbar")
        Screen2.setStatusBar(self.statusbar)

        self.retranslateUi(Screen2)
        QtCore.QMetaObject.connectSlotsByName(Screen2)

    def retranslateUi(self, Screen2):
        _translate = QtCore.QCoreApplication.translate
        Screen2.setWindowTitle(_translate("Screen2", "MainWindow"))
        self.pushButton.setText(_translate("Screen2", "Go to Screen 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen2 = QtWidgets.QMainWindow()
    ui = Ui_Screen2()
    ui.setupUi(Screen2)
    Screen2.show()
    sys.exit(app.exec_())
