# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from test import Ui_Screen2

class Ui_Screen1(object):

    def setupUi(self, Screen1):
        Screen1.setObjectName("Screen1")
        Screen1.resize(300, 400)
        Screen1.setMinimumSize(QtCore.QSize(300, 400))
        Screen1.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(Screen1)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 120, 131, 51))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.openSecondW)
        Screen1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Screen1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 26))
        self.menubar.setObjectName("menubar")
        Screen1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Screen1)
        self.statusbar.setObjectName("statusbar")
        Screen1.setStatusBar(self.statusbar)

        self.retranslateUi(Screen1)
        QtCore.QMetaObject.connectSlotsByName(Screen1)



    def retranslateUi(self, Screen1):
        _translate = QtCore.QCoreApplication.translate
        Screen1.setWindowTitle(_translate("Screen1", "MainWindow"))
        self.pushButton.setText(_translate("Screen1", "Go to Screen 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Screen1 = QtWidgets.QMainWindow()
    ui = Ui_Screen1()
    ui.setupUi(Screen1)
    Screen1.show()
    sys.exit(app.exec_())
